apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  namespace: devops-project
  labels:
    app: devops-demo
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo
          image: evanltx/devops-demo:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
